/**
 * THE ROUTE TABLE. One row per screen, in the mock's navigation order.
 *
 * Screen agents: DO NOT EDIT THIS FILE to build your screen. Your screen already
 * has a row here and a stub file at src/screens/<Id>.tsx — replace the body of
 * that file and nothing else. Touch this table only to change a path, a nav
 * group, an icon or a role requirement, and say so in your report.
 *
 * `titleKey` / `navKey` are catalog keys (packages/config/locales/{tr,en}.json).
 * Every one of them must exist in BOTH locales or the app throws on render;
 * test/i18n.test.ts asserts that for the whole table.
 */

/**
 * The four operator-facing groups, ordered by how a manager actually works:
 * start (daily work) → AI/agents → compliance → system setup. This replaces
 * the old monitor/work/governance/admin split, which mixed a manager's daily
 * tasks with engineer-only tooling. Nothing is hidden — every page still lives
 * in a group; the grouping just tells a first-time (even junior) admin where
 * each thing belongs.
 */
export type NavGroup = "start" | "compliance" | "ai" | "system";

export interface ScreenDef {
  /** Matches the mock's view id; also the stub component's file name, lowercased. */
  readonly id: string;
  /** Route path relative to the shell root, without a leading slash. */
  readonly path: string;
  /** Catalog key for the page heading. */
  readonly titleKey: string;
  /** Catalog key for the sidebar label; absent means "not in the sidebar". */
  readonly navKey?: string;
  readonly group?: NavGroup;
  /** Glyph from the mock's NAV table. */
  readonly icon?: string;
  /**
   * Roles that may SEE this entry in the navigation. Empty/absent = everyone.
   * This is a usability filter, NOT access control — the BFF authorises every
   * request regardless of what the sidebar shows. See RequireSession.tsx.
   */
  readonly roles?: readonly string[];
  /**
   * True for a screen whose backing capability is NOT live yet (the page shows
   * MaybeUnwired's "yayında değil"). The sidebar renders a small "yakında"
   * badge next to it — the entry stays visible and routable (deep links must
   * not break), it just stops pretending to be a working tool.
   */
  readonly soon?: true;
}

export const NAV_GROUPS: readonly NavGroup[] = ["start", "ai", "compliance", "system"];

export const NAV_GROUP_KEY: Readonly<Record<NavGroup, string>> = {
  start: "nav.group.start",
  compliance: "nav.group.compliance",
  ai: "nav.group.ai",
  system: "nav.group.system",
};

// Sidebar entries carry `navKey` + `group`; a screen WITHOUT them is still
// routable (reached from a link/row) but hidden from the sidebar. Mock-era
// static screens (live/jira/commands/greenfield/workmode/fanout/clarify/issues/
// mcp) are hidden here on purpose — they were gallery pages, not operator tools.
// Four groups, ordered by how an operator actually uses the platform.
export const SCREENS: readonly ScreenDef[] = [
  // ── ① İŞLER — a manager's daily work, in the order they do it ─────────────
  { id: "dash", path: "dash", titleKey: "screen.dash.title", navKey: "nav.dash", group: "start", icon: "▦" },
  // "tickets" (İş akışları) merged into the Panel — Dash renders TicketsList and
  // /tickets redirects to /dash (routes.tsx). No SCREENS row: it is not a page of
  // its own any more, just a redirect.
  // "Canlı akış" (pilot list + flow map) is gone with the retired pilot engine:
  // both views read the pilot's own 9-step state, a vocabulary the Temporal line
  // does not speak. Live work is the Panel's own list, over /studio/runs.
  { id: "sandbox", path: "sandbox", titleKey: "screen.sandbox.title", navKey: "nav.sandbox", group: "start", icon: "▶" },

  // ── ② AJANLAR — the manager's own AI config, simplified ──────────────────
  { id: "variants", path: "variants", titleKey: "screen.variants.title", navKey: "nav.variants", group: "ai", icon: "🤖" },
  { id: "knowledge", path: "knowledge", titleKey: "screen.knowledge.title", navKey: "nav.knowledge", group: "ai", icon: "📚" },
  { id: "template", path: "template", titleKey: "screen.template.title", navKey: "nav.template", group: "ai", icon: "📋" },
  { id: "doctemplate", path: "doctemplate", titleKey: "screen.doctemplate.title", navKey: "nav.doctemplate", group: "ai", icon: "📄" },
  { id: "eval", path: "eval", titleKey: "screen.eval.title", navKey: "nav.eval", group: "ai", icon: "🎯", soon: true },

  // ── ③ DENETİM — audit / compliance (jargon → Turkish); soon'lar dipte ────
  { id: "audit", path: "audit", titleKey: "screen.audit.title", navKey: "nav.audit", group: "compliance", icon: "🔒" },
  { id: "pii", path: "pii", titleKey: "screen.pii.title", navKey: "nav.pii", group: "compliance", icon: "🔏" },
  // Cost + LLM Gateway read the same two endpoints — now one page (AiUsageScreen)
  // with a "Maliyet" and a "Trafik" tab. /llm redirects to /cost?view=traffic.
  { id: "cost", path: "cost", titleKey: "screen.aiusage.title", navKey: "nav.aiusage", group: "compliance", icon: "₺" },
  { id: "security", path: "security", titleKey: "screen.security.title", navKey: "nav.security", group: "compliance", icon: "🛡", soon: true },
  { id: "evidence", path: "evidence", titleKey: "screen.evidence.title", navKey: "nav.evidence", group: "compliance", icon: "📦", soon: true },

  // ── ④ KURULUM — setup / infrastructure, rarely touched but reachable ─────
  // The guided wizard comes FIRST, above the expert screen it walks the user
  // through. A first-time operator who opens "Kurulum" should meet the page
  // that asks what they want to do, not the three-tab console that assumes they
  // already know. `soon` is deliberately absent: this ships working.
  { id: "setup", path: "setup", titleKey: "screen.setup.title", navKey: "nav.setup", group: "system", icon: "🧭" },
  { id: "projects", path: "projects", titleKey: "screen.projects.title", navKey: "nav.projects", group: "system", icon: "⇄" },
  { id: "notify", path: "notify", titleKey: "screen.notify.title", navKey: "nav.notify", group: "system", icon: "🔔" },
  { id: "users", path: "users", titleKey: "screen.users.title", navKey: "nav.users", group: "system", icon: "👥", roles: ["admin"] },
  { id: "settings", path: "settings", titleKey: "screen.settings.title", navKey: "nav.settings", group: "system", icon: "⚙" },
  { id: "health", path: "health", titleKey: "screen.health.title", navKey: "nav.health", group: "system", icon: "💚" },
  { id: "runners", path: "runners", titleKey: "screen.runners.title", navKey: "nav.runners", group: "system", icon: "🖥", soon: true },
  { id: "help", path: "help", titleKey: "screen.help.title", navKey: "nav.help", group: "system", icon: "📖" },

  /**
   * Parametreler menüde: motor bağlı, değerler CANLI.
   *
   * "Motora bağlı değilken gizli, bağlanınca geri gelir" diye çıkarılmıştı ve
   * geri getiren kod hiç yazılmadı — motor bağlandı, ekran gizli kaldı. Sonuç:
   * tarama sıklığı gibi operatörün ayarlaması gereken 21 değer, yalnız adresi
   * elle yazan birinin ulaşabildiği bir sayfada durdu.
   */
  { id: "params", path: "params", titleKey: "screen.params.title", navKey: "nav.params", group: "system", icon: "🎛", roles: ["admin", "tech-lead"] },

  // ── Sidebar'da GÖRÜNMEZ (rota olarak erişilir) ──────────────────────────
  // detail: bir tablo satırından açılır. Diğerleri maket-galeri artığı: statik
  // içerik, operatör aracı değil — rota kalır ama menüden çıkarıldı.
  { id: "detail", path: "detail/:ticket", titleKey: "screen.detail.title" },
  { id: "variant", path: "variant", titleKey: "screen.variant.title" },
  { id: "live", path: "live", titleKey: "screen.live.title" },
  { id: "fanout", path: "fanout", titleKey: "screen.fanout.title" },
  { id: "clarify", path: "clarify", titleKey: "screen.clarify.title" },
  { id: "workmode", path: "workmode", titleKey: "screen.workmode.title" },
  { id: "greenfield", path: "greenfield", titleKey: "screen.greenfield.title" },
  { id: "jira", path: "jira", titleKey: "screen.jira.title" },
  { id: "commands", path: "commands", titleKey: "screen.commands.title" },
  { id: "cache", path: "cache", titleKey: "screen.cache.title" },
  { id: "yaml", path: "yaml", titleKey: "screen.yaml.title" },
  { id: "mcp", path: "mcp", titleKey: "screen.mcp.title" },
  { id: "issues", path: "issues", titleKey: "screen.issues.title" },
];

/** `login` lives outside the shell (no sidebar, no session) — see routes.tsx. */
export const LOGIN_SCREEN: ScreenDef = {
  id: "login",
  path: "/login",
  titleKey: "screen.login.title",
};

export const ALL_SCREEN_IDS: readonly string[] = [
  ...SCREENS.map((screen) => screen.id),
  LOGIN_SCREEN.id,
];

export function screenById(id: string): ScreenDef | undefined {
  if (id === LOGIN_SCREEN.id) return LOGIN_SCREEN;
  return SCREENS.find((screen) => screen.id === id);
}
