import type { DemoRun } from "./runs.js";

/**
 * The payment domain's runs — the demo's centrepiece.
 *
 * UGURPAY-500 is the fan-out parent (M100): a credit-limit change that touches
 * four platforms, with a child per platform. Its children sit at four different
 * points on purpose — one at the PR gate, one running tests, one mid-
 * engineering, one stuck at the PO gate for sixteen days — because a fan-out
 * whose children all agree teaches nothing about coordinating them.
 *
 * The rest are standalone: a bug at the QA result gate, a ticket waiting on a
 * clarification answer, one queued behind the subscription pool, and one closed.
 */
export const UGURPAY_RUNS: readonly DemoRun[] = [
  {
    ticketKey: "UGURPAY-500",
    title: "Kredi limiti artırma akışı (koordinatör)",
    appId: null,
    mode: "full_auto",
    risk: "orta",
    step: "3",
    status: "running",
    reporter: "can.ozturk",
    assignee: "ayse.kaya",
    parentTicketKey: null,
    childTicketKeys: ["UGURPAY-501", "UGURPAY-502", "UGURPAY-503", "UGURPAY-504"],
    prId: null,
    costUsd: 18.4,
    tokensIn: 1_240_000,
    tokensOut: 186_000,
    startedHoursAgo: 144,
    updatedHoursAgo: 2,
  },
  {
    ticketKey: "UGURPAY-501",
    title: "Kredi limiti — API + web arayüzü",
    appId: "ugurpay",
    mode: "full_auto",
    risk: "orta",
    step: "12",
    status: "gate",
    reporter: "can.ozturk",
    assignee: "mert.demir",
    parentTicketKey: "UGURPAY-500",
    childTicketKeys: [],
    prId: 1841,
    costUsd: 6.2,
    tokensIn: 620_000,
    tokensOut: 94_000,
    startedHoursAgo: 144,
    updatedHoursAgo: 52,
  },
  {
    ticketKey: "UGURPAY-502",
    title: "Kredi limiti — iOS ekranı",
    appId: "ugurmobil-ios",
    mode: "full_auto",
    risk: "orta",
    step: "10",
    status: "running",
    reporter: "can.ozturk",
    assignee: "selin.aydin",
    parentTicketKey: "UGURPAY-500",
    childTicketKeys: [],
    prId: null,
    costUsd: 4.1,
    tokensIn: 410_000,
    tokensOut: 61_000,
    startedHoursAgo: 96,
    updatedHoursAgo: 1,
  },
  {
    ticketKey: "UGURPAY-503",
    title: "Kredi limiti — Android ekranı",
    appId: "ugurmobil-android",
    mode: "ai_assist",
    risk: "orta",
    step: "6a",
    status: "running",
    reporter: "can.ozturk",
    assignee: "baran.tekin",
    parentTicketKey: "UGURPAY-500",
    childTicketKeys: [],
    prId: null,
    costUsd: 3.0,
    tokensIn: 300_000,
    tokensOut: 44_000,
    startedHoursAgo: 96,
    updatedHoursAgo: 3,
  },
  {
    ticketKey: "UGURPAY-504",
    title: "Kredi limiti — masaüstü şube ekranı",
    appId: "ugurdesk",
    mode: "full_auto",
    risk: "orta",
    step: "4",
    status: "gate",
    reporter: "can.ozturk",
    assignee: "ayse.kaya",
    parentTicketKey: "UGURPAY-500",
    childTicketKeys: [],
    prId: null,
    costUsd: 1.4,
    tokensIn: 140_000,
    tokensOut: 21_000,
    startedHoursAgo: 386,
    updatedHoursAgo: 386,
  },
  {
    ticketKey: "UGURPAY-123",
    title: "İade akışında tutar yuvarlama hatası",
    appId: "ugurpay",
    mode: "full_auto",
    risk: "dusuk",
    step: "11",
    status: "gate",
    reporter: "deniz.yilmaz",
    assignee: "mert.demir",
    parentTicketKey: null,
    childTicketKeys: [],
    prId: 1836,
    costUsd: 2.9,
    tokensIn: 290_000,
    tokensOut: 38_000,
    startedHoursAgo: 26,
    updatedHoursAgo: 1,
  },
  {
    ticketKey: "UGURPAY-712",
    title: "Kart aidatı iade talebi akışı",
    appId: "ugurpay",
    mode: "full_auto",
    risk: "orta",
    step: "2b",
    status: "gate",
    reporter: "can.ozturk",
    assignee: null,
    parentTicketKey: null,
    childTicketKeys: [],
    prId: null,
    costUsd: 0.04,
    tokensIn: 4_100,
    tokensOut: 900,
    startedHoursAgo: 21,
    updatedHoursAgo: 20,
  },
  {
    ticketKey: "UGURPAY-689",
    title: "Ekstre PDF tasarım yenileme",
    appId: "ugurpay",
    mode: "full_auto",
    risk: "dusuk",
    step: "3",
    status: "queued",
    reporter: "can.ozturk",
    assignee: null,
    parentTicketKey: null,
    childTicketKeys: [],
    prId: null,
    costUsd: 0.3,
    tokensIn: 31_000,
    tokensOut: 4_200,
    startedHoursAgo: 3,
    updatedHoursAgo: 1,
  },
  {
    ticketKey: "UGURPAY-478",
    title: "Fatura ödemede sık kullanılanlar listesi",
    appId: "ugurpay",
    mode: "full_auto",
    risk: "dusuk",
    step: "13",
    status: "done",
    reporter: "can.ozturk",
    assignee: "mert.demir",
    parentTicketKey: null,
    childTicketKeys: [],
    prId: 1802,
    costUsd: 3.1,
    tokensIn: 312_000,
    tokensOut: 47_000,
    startedHoursAgo: 190,
    updatedHoursAgo: 160,
  },
];
