import type { DemoRun } from "./runs.js";

/**
 * The web, mobile and desktop runs.
 *
 * These carry the states the payment set does not: a `handover` (mode
 * `human_only` — a person is working and Maestro only watches and collects
 * evidence), two failures with different causes (UGURDESK-45 red on CI,
 * UGURDESK-52 blocked by a fail-closed secret scan, M27), a `kritik` run at the
 * CI gate, and one closed ticket whose evidence package carries the `dusuk`
 * tier's two-gate approval chain.
 */
export const OTHER_RUNS: readonly DemoRun[] = [
  {
    ticketKey: "UGURWEB-88",
    title: "Kampanya banner bileşeni",
    appId: "ugurweb",
    mode: "human_lead",
    risk: "dusuk",
    step: "6a",
    status: "running",
    reporter: "ayse.kaya",
    assignee: "deniz.yilmaz",
    parentTicketKey: null,
    childTicketKeys: [],
    prId: null,
    costUsd: 0.8,
    tokensIn: 82_000,
    tokensOut: 11_000,
    startedHoursAgo: 70,
    updatedHoursAgo: 4,
  },
  {
    ticketKey: "UGURWEB-72",
    title: "Giriş sayfası captcha entegrasyonu",
    appId: "ugurweb",
    mode: "full_auto",
    risk: "orta",
    step: "9",
    status: "gate",
    reporter: "ayse.kaya",
    assignee: "selin.aydin",
    parentTicketKey: null,
    childTicketKeys: [],
    prId: null,
    costUsd: 2.2,
    tokensIn: 221_000,
    tokensOut: 33_000,
    startedHoursAgo: 50,
    updatedHoursAgo: 4,
  },
  {
    ticketKey: "UGURWEB-95",
    title: "A/B test altyapısı temizliği",
    appId: "ugurweb",
    mode: "human_only",
    risk: "dusuk",
    step: "6a",
    status: "handover",
    reporter: "mert.demir",
    assignee: "baran.tekin",
    parentTicketKey: null,
    childTicketKeys: [],
    prId: null,
    costUsd: 0,
    tokensIn: 0,
    tokensOut: 0,
    startedHoursAgo: 27,
    updatedHoursAgo: 6,
  },
  {
    ticketKey: "UGURMOB-201",
    title: "Face ID ile hızlı giriş",
    appId: "ugurmobil-ios",
    mode: "full_auto",
    risk: "kritik",
    step: "10b",
    status: "running",
    reporter: "can.ozturk",
    assignee: "selin.aydin",
    parentTicketKey: null,
    childTicketKeys: [],
    prId: 312,
    costUsd: 3.8,
    tokensIn: 384_000,
    tokensOut: 58_000,
    startedHoursAgo: 48,
    updatedHoursAgo: 2,
  },
  {
    ticketKey: "UGURMOB-188",
    title: "Bildirim izinleri — Android 15 uyumu",
    appId: "ugurmobil-android",
    mode: "full_auto",
    risk: "dusuk",
    step: "5",
    status: "gate",
    reporter: "selin.aydin",
    assignee: "baran.tekin",
    parentTicketKey: null,
    childTicketKeys: [],
    prId: null,
    costUsd: 0.9,
    tokensIn: 94_000,
    tokensOut: 13_000,
    startedHoursAgo: 7,
    updatedHoursAgo: 3,
  },
  {
    ticketKey: "UGURDESK-45",
    title: "Rapor ekranı dışa aktarma",
    appId: "ugurdesk",
    mode: "full_auto",
    risk: "dusuk",
    step: "10",
    status: "fail",
    reporter: "ayse.kaya",
    assignee: "baran.tekin",
    parentTicketKey: null,
    childTicketKeys: [],
    prId: null,
    costUsd: 1.7,
    tokensIn: 172_000,
    tokensOut: 26_000,
    startedHoursAgo: 45,
    updatedHoursAgo: 2,
  },
  {
    ticketKey: "UGURDESK-52",
    title: "Toplu EFT dosyası içe aktarma",
    appId: "ugurdesk",
    mode: "full_auto",
    risk: "kritik",
    step: "6b",
    status: "fail",
    reporter: "ayse.kaya",
    assignee: "baran.tekin",
    parentTicketKey: null,
    childTicketKeys: [],
    prId: null,
    costUsd: 1.3,
    tokensIn: 131_000,
    tokensOut: 19_000,
    startedHoursAgo: 6,
    updatedHoursAgo: 1,
  },
  {
    ticketKey: "UGURDESK-39",
    title: "Yazdırma önizleme kilitleniyor",
    appId: "ugurdesk",
    mode: "full_auto",
    risk: "dusuk",
    step: "13",
    status: "done",
    reporter: "deniz.yilmaz",
    assignee: "baran.tekin",
    parentTicketKey: null,
    childTicketKeys: [],
    prId: 204,
    costUsd: 0.9,
    tokensIn: 91_000,
    tokensOut: 14_000,
    startedHoursAgo: 300,
    updatedHoursAgo: 280,
  },
];
